-- Safe defaults only. User overrides are loaded by Systems.ConfigStore.
return {
    FarmRange = 700,
    TargetAcquireInterval = 0.25,
    TargetSwitchMargin = 2,
    TargetDecisionInterval = 0.25,
    PreferredCombatDistance = 70,
    AttackRange = 15,
    NormalSkillRange = 85,
    BossSkillRange = 100,
    RespawnGraceDuration = 6.5,
    AttackCooldown = 0.12,
    QCooldownMin = 0.3,
    QCooldownMax = 0.5,
    ECooldown = 0.4,
    TargetWalkSpeed = 23,
    DodgeEnabled = true,
    AutoReplay = true,
    AutoStart = true,
    WebhookEnabled = false,
    WebhookURL = "",
    FarmEnabled = false,
    ShowHUD = true,
}
