-- Shared in-memory runtime state. Persistence belongs exclusively to Systems.ConfigStore.

local Runtime = {}

function Runtime.create(skillFX)
local state = {
	JumpStillSince = os.clock(),
	JumpBestDistance = math.huge,
	JumpBestVertical = math.huge,
	JumpBurstUntil = 0,
	JumpBurstTaskRunning = false,
	JumpBurstGeneration = 0,
	ReplayAwaitingClose = nil :: GuiButton?,
	ReplayPhase = "IDLE",
	ReplayPhaseEnteredAt = 0,
	ReplayRetries = 0,
	ReplayResultScanDirty = true,
	ReplayArmedAt = 0,
	ReplayLastActionAt = -math.huge,
	ReplayModal = nil :: GuiObject?,
	ReplayCompletionRoot = nil :: GuiObject?,
	ReplayOpener = nil :: GuiButton?,
	ReplayConfirmRoot = nil :: GuiObject?,
	ReplayLastGuiScanAt = -math.huge,
	ReplayOpenerMissingReported = false,
	ReplayCompletionDetected = false,
	BossDiedConnection = nil :: RBXScriptConnection?,
	BossDiedTarget = nil :: Model?,
	StartDebugMarker = nil :: GuiObject?,
	StartDebugButton = nil :: GuiButton?,
	StartMarker = nil :: GuiObject?,
	StartButton = nil :: GuiButton?,
	LastStartMarkerScanAt = -math.huge,
	DungeonFinishedLastState = false,
	ActiveDungeonRoot = nil :: Instance?,
	DungeonIdentity = nil :: Instance?,
	EnemyFolders = {} :: { [Instance]: boolean },
	EnemyCandidates = {} :: { [Model]: boolean },
	DungeonFinishedInstance = nil :: BoolValue?,
	PreviousDungeonFinishedInstance = nil :: BoolValue?,
	FightingBossInstance = nil :: BoolValue?,
	LastFightingBossState = false,
	FightingBossSeenThisRound = false,
	EnemyFolderInstance = nil :: Instance?,
	DungeonTimeInstance = nil :: ValueBase?,
	DungeonTimeText = nil :: GuiObject?,
	LastDungeonReferenceSearchAt = -math.huge,
	LastDungeonStateCheckAt = 0,
	LastFallbackTargetScanAt = -math.huge,
	LastHUDUpdateAt = -math.huge,
	LastStatsSampleAt = -math.huge,
	PingMs = 0,
	SmoothedFPS = 0,
	WebhookLastByEvent = {} :: { [string]: number },
	ObsidianLibrary = nil,
	ObsidianWindow = nil,
	ObsidianLabels = {} :: { [string]: any },
	ReplayResultKind = nil :: string?,
	Activity = "IDLE",
	ActivityDetail = "",
	ActiveSkillModels = skillFX.Models,
	ActiveSkillHitboxes = skillFX.Hitboxes,
	ReplayYesButton = nil :: GuiButton?,
	ReplayDebugButton = nil :: GuiButton?,
	RoundResetSerial = 0,
	RespawnGraceUntil = 0,
	VerticalPathTarget = nil :: Model?,
	VerticalPathGoal = nil :: Vector3?,
	LastSkillContextSignature = "",
	RoundPhase = "UNKNOWN",
	DungeonCacheDirty = true,
	DungeonRebuildScheduled = false,
	DungeonBootstrapped = false,
	LastTargetDecisionAt = -math.huge,
	DummyCache = {} :: { [Model]: boolean },
	HazardHistory = {} :: { [BasePart]: { LastRadius: number, LastPosition: Vector3, LastSeenAt: number } },
	LastTimerSource = nil :: Instance?,
	LastTimerValue = nil :: number?,
	LastTimerScanAt = -math.huge,
	CurrentHazardRadius = 0,
	CurrentHazardGrowing = false,
	PathBlockedConnection = nil :: RBXScriptConnection?,
	ActivePathGeneration = 0,
	WaypointIssueSerial = 0,
	DodgeStartedAt = 0,
	LastStartClickAt = -math.huge,
	CharacterBindSerial = 0,
	DefaultAutoRotate = true,
	DefaultWalkSpeed = 16,
	LastGoalRefreshAt = 0,
	LastDodgeGoalAttemptAt = -math.huge,
	LastHazardRefreshAt = -math.huge,
}

	return state
end

return Runtime
